#! /bin/bash

apply_korean_backtick() {
    # Change won to backtick
    local target_dir=$HOME/Library/KeyBindings
    mkdir -p $target_dir
    cat > $target_dir/DefaultkeyBinding.dict <<- "EOF"
{
    "₩" = ("insertText:", "`");
}
EOF
}

apply_korean_backtick
